In [1]:
import numpy as np

In [6]:
a = np.random.randint(9 , size=10)

In [7]:
a

array([1, 2, 0, 4, 6, 4, 2, 3, 3, 7])

In [18]:
for i in range(len(a)-1):
    for j in range(len(a) - 1  - i):
        if a[j] > a[j+1]:
            a[j] , a[j+1] = a[j+1] , a[j]
print(a)

[0 1 2 2 3 3 4 4 6 7]


In [15]:
a

array([0, 1, 2, 2, 3, 3, 4, 4, 6, 7])